name: CI

on:
  # Triggers the workflow on push or pull request events but only for the mawa branch
  push:
    branches: [ mawa ]
  pull_request:
    branches: [ mawa ]

jobs:
    repoman:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: lucianposton/repoman-ebuild-qa-action@v1
              with:
                repoman_args: -d --mode=scan
                portage_version: latest
